plugins {
    id 'java'
    id 'maven-publish'
}

group = 'com.github.tth05'
var ver = System.getenv("GITHUB_REF") ?: "dev"
version = ver.replaceAll("^refs/tags/v", "")

repositories {
    mavenCentral()
}

dependencies {
    testImplementation 'io.github.classgraph:classgraph:4.8.193'
    testImplementation platform('org.junit:junit-bom:6.1.3')
    testImplementation 'org.junit.jupiter:junit-jupiter'
    testRuntimeOnly 'org.junit.platform:junit-platform-launcher'
}

test {
    useJUnitPlatform()

    testLogging {
        showStandardStreams = true
    }
}
tasks.register('buildNativeLibrary', Exec) {
    workingDir "${projectDir}/jindex-rs"
    commandLine "cargo", "build", "--release"

    doLast {
        copy {
            from "${projectDir}/jindex-rs/target/release"
            into "${projectDir}/src/main/resources/jindex_natives"
            include "jindex_rs.dll"
        }
    }
}

tasks.named('processResources') {
    dependsOn tasks.named('buildNativeLibrary')
}

java {
    toolchain.languageVersion = JavaLanguageVersion.of(21)
    withSourcesJar()
    withJavadocJar()
}

tasks.withType(JavaCompile).configureEach {
    options.release = 21
}

publishing {
    publications {
        mavenJava(MavenPublication) {
            from components.java
        }
    }
    repositories {
        maven {
            url = "https://packagecloud.io/tth05/repo/java/maven2/"
            credentials {
                username = System.getenv("PACKAGECLOUD_TOKEN")
                password = ""
            }
        }
    }
}
