[package]
name = "jindex-rs"
version = "0.1.0"
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
ascii = "1.0.0"
anyhow = "1.0.44"
jni = "0.19.0"
cafebabe = "0.5.0"

[lib]
crate_type = ["cdylib"]