name: Publish

on:
  push:
    tags:
      - 'v*'

jobs:
  build_and_publish:
    name: Publish
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions-rs/toolchain@v1
        with:
          toolchain: nightly
          default: true
          profile: minimal
      - uses: Swatinem/rust-cache@v1
        with:
          working-directory: jindex-rs
      - name: Build with Gradle
        env:
          PACKAGECLOUD_TOKEN: ${{ secrets.PACKAGECLOUD_TOKEN }}
        run: ./gradlew.bat build publish -x test
